# Generated by Django 2.2.15 on 2020-11-02 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('fontsize', models.IntegerField()),
                ('upload_music', models.FileField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('created', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=post.models.upload_location)),
                ('emotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Emotion')),
            ],
        ),
        migrations.CreateModel(
            name='PostColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.TextField()),
                ('music_artist', models.TextField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('emotion', models.IntegerField()),
                ('tags', models.ManyToManyField(related_name='stickers', to='post.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='PostSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('deg', models.IntegerField()),
                ('top', models.IntegerField()),
                ('left', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='post.Post')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Sticker')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='font',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostFont'),
        ),
        migrations.AddField(
            model_name='post',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Pattern'),
        ),
        migrations.AddField(
            model_name='post',
            name='postcolor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostColor'),
        ),
        migrations.AddField(
            model_name='post',
            name='recommend_music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.RecommendMusic'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
