# Generated by Django 2.2.15 on 2020-11-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201103_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.Emotion'),
        ),
    ]
