# Generated by Django 2.2.15 on 2020-10-21 10:53

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201021_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_location),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
