# Generated by Django 2.2.15 on 2020-11-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
        ('post', '0003_post_user_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_emotion',
        ),
        migrations.AddField(
            model_name='post',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='text.DailyReport'),
        ),
    ]
