# Generated by Django 2.2.15 on 2020-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20201029_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
