# Generated by Django 2.2.15 on 2020-10-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_auto_20201029_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Emotion'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='score',
            field=models.FloatField(),
        ),
    ]
