# Generated by Django 2.2.15 on 2020-10-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0007_auto_20201029_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='emotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Emotion'),
        ),
    ]
