# Generated by Django 2.2.15 on 2020-10-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0008_auto_20201029_1801'),
        ('text', '0002_auto_20201029_1643'),
    ]

    operations = [
    ]
