# Generated by Django 2.2.15 on 2020-10-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201021_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststicker',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='post.Post'),
        ),
    ]
