# Generated by Django 2.2.15 on 2020-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('post', '0005_auto_20201022_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='emotion',
            table='post_emotion',
        ),
        migrations.AlterModelTable(
            name='pattern',
            table='post_pattern',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post_post',
        ),
        migrations.AlterModelTable(
            name='postcolor',
            table='post_postcolor',
        ),
        migrations.AlterModelTable(
            name='postfont',
            table='post_postfont',
        ),
        migrations.AlterModelTable(
            name='poststicker',
            table='post_poststicker',
        ),
        migrations.AlterModelTable(
            name='sticker',
            table='post_sticker',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='post_tag',
        ),
    ]
