# Generated by Django 2.2.15 on 2020-10-30 06:14

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201027_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.TextField()),
                ('music_artist', models.TextField()),
                ('path', models.TextField()),
            ],
            options={
                'db_table': 'post_recommendmusic',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='music_artist',
        ),
        migrations.RemoveField(
            model_name='post',
            name='music_name',
        ),
        migrations.AddField(
            model_name='post',
            name='upload_music',
            field=models.FileField(blank=True, null=True, upload_to=post.models.upload_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Emotion'),
        ),
        migrations.AddField(
            model_name='post',
            name='recommend_music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.RecommendMusic'),
        ),
    ]
