# Generated by Django 2.2.15 on 2020-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('post', '0002_auto_20201112_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommend_like',
            field=models.ManyToManyField(related_name='recommend_like_music', to='post.RecommendMusic'),
        ),
        migrations.AddField(
            model_name='user',
            name='search_like',
            field=models.ManyToManyField(related_name='search_like_music', to='post.SearchMusic'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
