# Generated by Django 2.2.15 on 2020-11-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201104_2218'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='like_user', to='post.RecommendMusic'),
        ),
    ]
