# Generated by Django 2.2.15 on 2020-11-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201103_1502'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='emotions',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user_emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_report', to='post.Emotion'),
        ),
    ]
