# Generated by Django 2.2.15 on 2020-11-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='user_emotion',
        ),
    ]
