# Generated by Django 2.2.15 on 2020-11-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_remove_dailyreport_user_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='post',
        ),
    ]
