# Generated by Django 2.2.15 on 2020-10-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='tags',
            field=models.ManyToManyField(related_name='stickers', to='post.Tag'),
        ),
        migrations.DeleteModel(
            name='StickerTag',
        ),
    ]
