# Generated by Django 2.2.15 on 2020-11-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201111_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(blank=True, max_length=30, null=True)),
                ('video_id', models.CharField(max_length=20)),
                ('cover', models.TextField(blank=True, null=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_musics', to='post.Emotion')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='search_music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_music', to='post.SearchMusic'),
        ),
        migrations.AddField(
            model_name='searchmusic',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.Post'),
        ),
    ]
