# Generated by Django 2.2.15 on 2020-11-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201109_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendmusic',
            name='cover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
