# Generated by Django 2.2.15 on 2020-11-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201107_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='score',
        ),
    ]
