# Generated by Django 2.2.15 on 2020-11-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201109_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendmusic',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
