# Generated by Django 2.2.15 on 2020-11-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_sticker_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='post.Emotion'),
        ),
    ]
