# Generated by Django 2.2.15 on 2020-10-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201021_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='music',
            new_name='music_artist',
        ),
        migrations.AddField(
            model_name='post',
            name='music_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
