# Generated by Django 2.2.15 on 2020-11-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201111_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poststicker',
            old_name='deg',
            new_name='rotation',
        ),
        migrations.RenameField(
            model_name='poststicker',
            old_name='left',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='poststicker',
            old_name='top',
            new_name='y',
        ),
    ]
