# Generated by Django 2.2.15 on 2020-11-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201109_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fontsize',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postcolor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_music',
        ),
        migrations.AlterField(
            model_name='recommendmusic',
            name='artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
