# Generated by Django 2.2.15 on 2020-11-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201111_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendmusic',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='searchmusic',
            old_name='title',
            new_name='name',
        ),
    ]
