# Generated by Django 2.2.15 on 2020-11-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201111_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serch_music', to='post.RecommendMusic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recommend_music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommend_music', to='post.RecommendMusic'),
        ),
    ]
